// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRGsxIFeMQtAhzZMLYBGAyHqzzjlpUwB4',
    appId: '1:28770562950:web:ec69674d32c5ad355a7207',
    messagingSenderId: '28770562950',
    projectId: 'chat-app-5de63',
    authDomain: 'chat-app-5de63.firebaseapp.com',
    storageBucket: 'chat-app-5de63.firebasestorage.app',
    measurementId: 'G-XSSL91RZT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADITaDWy8xj5qo3rSb5FeHQgHjQhGlpFA',
    appId: '1:28770562950:android:3abc1c0ec242b38d5a7207',
    messagingSenderId: '28770562950',
    projectId: 'chat-app-5de63',
    storageBucket: 'chat-app-5de63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDciI0NGvf5BMa2rGKvwbEGnBkQyC-QO1k',
    appId: '1:28770562950:ios:79e83abd710061ba5a7207',
    messagingSenderId: '28770562950',
    projectId: 'chat-app-5de63',
    storageBucket: 'chat-app-5de63.firebasestorage.app',
    iosBundleId: 'com.example.text2sign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDciI0NGvf5BMa2rGKvwbEGnBkQyC-QO1k',
    appId: '1:28770562950:ios:79e83abd710061ba5a7207',
    messagingSenderId: '28770562950',
    projectId: 'chat-app-5de63',
    storageBucket: 'chat-app-5de63.firebasestorage.app',
    iosBundleId: 'com.example.text2sign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJEsisx1vBvPQJ1e1NPQxOpr0Fx0Sms7E',
    appId: '1:28770562950:web:8218584b306fd1d35a7207',
    messagingSenderId: '28770562950',
    projectId: 'chat-app-5de63',
    authDomain: 'chat-app-5de63.firebaseapp.com',
    storageBucket: 'chat-app-5de63.firebasestorage.app',
    measurementId: 'G-29BNZC3Z3Q',
  );
}
